//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     ANTLR Version: 4.13.2
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// Generated from ./SysY.g4 by ANTLR 4.13.2

// Unreachable code detected
#pragma warning disable 0162
// The variable '...' is assigned but its value is never used
#pragma warning disable 0219
// Missing XML comment for publicly visible type or member '...'
#pragma warning disable 1591
// Ambiguous reference in cref attribute
#pragma warning disable 419

using Antlr4.Runtime.Misc;
using IParseTreeListener = Antlr4.Runtime.Tree.IParseTreeListener;
using IToken = Antlr4.Runtime.IToken;

/// <summary>
/// This interface defines a complete listener for a parse tree produced by
/// <see cref="SysYParser"/>.
/// </summary>
[System.CodeDom.Compiler.GeneratedCode("ANTLR", "4.13.2")]
[System.CLSCompliant(false)]
public interface ISysYListener : IParseTreeListener {
	/// <summary>
	/// Enter a parse tree produced by <see cref="SysYParser.compilationUnit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterCompilationUnit([NotNull] SysYParser.CompilationUnitContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SysYParser.compilationUnit"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitCompilationUnit([NotNull] SysYParser.CompilationUnitContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SysYParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclaration([NotNull] SysYParser.DeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SysYParser.declaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclaration([NotNull] SysYParser.DeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SysYParser.bType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBType([NotNull] SysYParser.BTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SysYParser.bType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBType([NotNull] SysYParser.BTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SysYParser.constantDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstantDeclaration([NotNull] SysYParser.ConstantDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SysYParser.constantDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstantDeclaration([NotNull] SysYParser.ConstantDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SysYParser.constDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstDefinition([NotNull] SysYParser.ConstDefinitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SysYParser.constDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstDefinition([NotNull] SysYParser.ConstDefinitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SysYParser.constInitValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstInitValue([NotNull] SysYParser.ConstInitValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SysYParser.constInitValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstInitValue([NotNull] SysYParser.ConstInitValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SysYParser.variableDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariableDeclaration([NotNull] SysYParser.VariableDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SysYParser.variableDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariableDeclaration([NotNull] SysYParser.VariableDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Definition</c>
	/// labeled alternative in <see cref="SysYParser.variableDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDefinition([NotNull] SysYParser.DefinitionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Definition</c>
	/// labeled alternative in <see cref="SysYParser.variableDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDefinition([NotNull] SysYParser.DefinitionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Declare</c>
	/// labeled alternative in <see cref="SysYParser.variableDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterDeclare([NotNull] SysYParser.DeclareContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Declare</c>
	/// labeled alternative in <see cref="SysYParser.variableDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitDeclare([NotNull] SysYParser.DeclareContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SysYParser.initialValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterInitialValue([NotNull] SysYParser.InitialValueContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SysYParser.initialValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitInitialValue([NotNull] SysYParser.InitialValueContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SysYParser.functionDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionDefinition([NotNull] SysYParser.FunctionDefinitionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SysYParser.functionDefinition"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionDefinition([NotNull] SysYParser.FunctionDefinitionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SysYParser.functionType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionType([NotNull] SysYParser.FunctionTypeContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SysYParser.functionType"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionType([NotNull] SysYParser.FunctionTypeContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SysYParser.parameterDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParameterDeclaration([NotNull] SysYParser.ParameterDeclarationContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SysYParser.parameterDeclaration"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParameterDeclaration([NotNull] SysYParser.ParameterDeclarationContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SysYParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlock([NotNull] SysYParser.BlockContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SysYParser.block"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlock([NotNull] SysYParser.BlockContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SysYParser.blockItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBlockItem([NotNull] SysYParser.BlockItemContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SysYParser.blockItem"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBlockItem([NotNull] SysYParser.BlockItemContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Assignment</c>
	/// labeled alternative in <see cref="SysYParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAssignment([NotNull] SysYParser.AssignmentContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Assignment</c>
	/// labeled alternative in <see cref="SysYParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAssignment([NotNull] SysYParser.AssignmentContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>NormalExpression</c>
	/// labeled alternative in <see cref="SysYParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterNormalExpression([NotNull] SysYParser.NormalExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>NormalExpression</c>
	/// labeled alternative in <see cref="SysYParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitNormalExpression([NotNull] SysYParser.NormalExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>If</c>
	/// labeled alternative in <see cref="SysYParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterIf([NotNull] SysYParser.IfContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>If</c>
	/// labeled alternative in <see cref="SysYParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitIf([NotNull] SysYParser.IfContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>While</c>
	/// labeled alternative in <see cref="SysYParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterWhile([NotNull] SysYParser.WhileContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>While</c>
	/// labeled alternative in <see cref="SysYParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitWhile([NotNull] SysYParser.WhileContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Break</c>
	/// labeled alternative in <see cref="SysYParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterBreak([NotNull] SysYParser.BreakContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Break</c>
	/// labeled alternative in <see cref="SysYParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitBreak([NotNull] SysYParser.BreakContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Continue</c>
	/// labeled alternative in <see cref="SysYParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterContinue([NotNull] SysYParser.ContinueContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Continue</c>
	/// labeled alternative in <see cref="SysYParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitContinue([NotNull] SysYParser.ContinueContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Return</c>
	/// labeled alternative in <see cref="SysYParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterReturn([NotNull] SysYParser.ReturnContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Return</c>
	/// labeled alternative in <see cref="SysYParser.statement"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitReturn([NotNull] SysYParser.ReturnContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SysYParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterExpression([NotNull] SysYParser.ExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SysYParser.expression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitExpression([NotNull] SysYParser.ExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>ArrayAccess</c>
	/// labeled alternative in <see cref="SysYParser.leftValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterArrayAccess([NotNull] SysYParser.ArrayAccessContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>ArrayAccess</c>
	/// labeled alternative in <see cref="SysYParser.leftValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitArrayAccess([NotNull] SysYParser.ArrayAccessContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>VariableAccess</c>
	/// labeled alternative in <see cref="SysYParser.leftValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterVariableAccess([NotNull] SysYParser.VariableAccessContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>VariableAccess</c>
	/// labeled alternative in <see cref="SysYParser.leftValue"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitVariableAccess([NotNull] SysYParser.VariableAccessContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>LeftValueAccess</c>
	/// labeled alternative in <see cref="SysYParser.primaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLeftValueAccess([NotNull] SysYParser.LeftValueAccessContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>LeftValueAccess</c>
	/// labeled alternative in <see cref="SysYParser.primaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLeftValueAccess([NotNull] SysYParser.LeftValueAccessContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Constant</c>
	/// labeled alternative in <see cref="SysYParser.primaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstant([NotNull] SysYParser.ConstantContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Constant</c>
	/// labeled alternative in <see cref="SysYParser.primaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstant([NotNull] SysYParser.ConstantContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Parentheses</c>
	/// labeled alternative in <see cref="SysYParser.primaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterParentheses([NotNull] SysYParser.ParenthesesContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Parentheses</c>
	/// labeled alternative in <see cref="SysYParser.primaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitParentheses([NotNull] SysYParser.ParenthesesContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>UnaryPlus</c>
	/// labeled alternative in <see cref="SysYParser.unaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnaryPlus([NotNull] SysYParser.UnaryPlusContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>UnaryPlus</c>
	/// labeled alternative in <see cref="SysYParser.unaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnaryPlus([NotNull] SysYParser.UnaryPlusContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>UnaryMinus</c>
	/// labeled alternative in <see cref="SysYParser.unaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterUnaryMinus([NotNull] SysYParser.UnaryMinusContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>UnaryMinus</c>
	/// labeled alternative in <see cref="SysYParser.unaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitUnaryMinus([NotNull] SysYParser.UnaryMinusContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>LogicalNot</c>
	/// labeled alternative in <see cref="SysYParser.unaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLogicalNot([NotNull] SysYParser.LogicalNotContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>LogicalNot</c>
	/// labeled alternative in <see cref="SysYParser.unaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLogicalNot([NotNull] SysYParser.LogicalNotContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>Primary</c>
	/// labeled alternative in <see cref="SysYParser.unaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterPrimary([NotNull] SysYParser.PrimaryContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>Primary</c>
	/// labeled alternative in <see cref="SysYParser.unaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitPrimary([NotNull] SysYParser.PrimaryContext context);
	/// <summary>
	/// Enter a parse tree produced by the <c>FunctionCall</c>
	/// labeled alternative in <see cref="SysYParser.unaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterFunctionCall([NotNull] SysYParser.FunctionCallContext context);
	/// <summary>
	/// Exit a parse tree produced by the <c>FunctionCall</c>
	/// labeled alternative in <see cref="SysYParser.unaryExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitFunctionCall([NotNull] SysYParser.FunctionCallContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SysYParser.multiplicativeExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterMultiplicativeExpression([NotNull] SysYParser.MultiplicativeExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SysYParser.multiplicativeExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitMultiplicativeExpression([NotNull] SysYParser.MultiplicativeExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SysYParser.additiveExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterAdditiveExpression([NotNull] SysYParser.AdditiveExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SysYParser.additiveExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitAdditiveExpression([NotNull] SysYParser.AdditiveExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SysYParser.relationalExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterRelationalExpression([NotNull] SysYParser.RelationalExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SysYParser.relationalExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitRelationalExpression([NotNull] SysYParser.RelationalExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SysYParser.equalityExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterEqualityExpression([NotNull] SysYParser.EqualityExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SysYParser.equalityExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitEqualityExpression([NotNull] SysYParser.EqualityExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SysYParser.logicalAndExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLogicalAndExpression([NotNull] SysYParser.LogicalAndExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SysYParser.logicalAndExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLogicalAndExpression([NotNull] SysYParser.LogicalAndExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SysYParser.logicalOrExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterLogicalOrExpression([NotNull] SysYParser.LogicalOrExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SysYParser.logicalOrExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitLogicalOrExpression([NotNull] SysYParser.LogicalOrExpressionContext context);
	/// <summary>
	/// Enter a parse tree produced by <see cref="SysYParser.constExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void EnterConstExpression([NotNull] SysYParser.ConstExpressionContext context);
	/// <summary>
	/// Exit a parse tree produced by <see cref="SysYParser.constExpression"/>.
	/// </summary>
	/// <param name="context">The parse tree.</param>
	void ExitConstExpression([NotNull] SysYParser.ConstExpressionContext context);
}
